export const authConstants={

    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE:"LOGIN_FAILUR",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE"
}

export const userConstants={

    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE"
}

export const resultConstants={

        GET_RESULT_REQUEST:"GET_RESULT_REQUEST",
        GET_RESULT_SUCCESS:" GET_RESULT_SUCCESS",
        GET_RESULT_FAILURE:"GET_RESULT_FAILURE",
        ADD_NEW_RESULT_REQUEST:"ADD_NEW_RESULT_REQUEST",
        ADD_NEW_RESULT_SUCCESS:" ADD_NEW_RESULT_SUCCESS",
        ADD_NEW_RESULT_FAILURE:"ADD_NEW_RESULT_FAILURE"   
}
export const studentConstants={

        GET_ALL_STUDENT_REQUEST:"GET_STUDENT_REQUEST",
        GET__STUDENT_SUCCESS:" GET_STUDENT_SUCCESS",
        GET__STUDENT_FAILURE:"GET_STUDENT_FAILURE",
        ADD_NEW_STUDENT_REQUEST:"ADD_NEW_STUDENT_REQUEST",
        ADD_NEW_STUDENT_SUCCESS:" ADD_NEW_STUDENT_SUCCESS",
        ADD_NEW_STUDENT_FAILURE:"ADD_NEW_STUDENT_FAILURE"   
}